### PR TITLE
Fix can only flip around original axis

### PR DESCRIPTION
**Pull request by plocket**
My bad. Now you can rotate and then flip if you need to flip around some other axis.

Needs more experiments to find out if this is really the way to do it.

### CODE REVIEW

**Review by michaelaltmann — APPROVED** [review]
Looks good

**Comment by michaelaltmann** [comment]
The rotate+flip seem good for images, but wonky for PDFs

**Comment by plocket** [comment]
This makes it less confusing, but I think it actually limits the rotation to just one axis (which I should have guessed, x and y and all that). I think this isn't the right move. The only sensical way, I think, would be to have two buttons - flip horizontally and flip vertically - that would adjust what they're doing based on rotation so that things would always be flipping in those orientations from the viewpoint of the user.

**Comment by plocket** [comment]
Not sure I can tackle that today.

**Pull request closed without merging**
